CREATE TABLE `team_shift_timing_configs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `team_id` int NOT NULL,
  `account_id` int NOT NULL,
  `shift_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shift_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `color_code` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT '#007bff',
  `order_index` int DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `is_default` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_team_shift` (`team_id`,`account_id`,`shift_code`),
  KEY `idx_team_shift_timing_team` (`team_id`),
  KEY `idx_team_shift_timing_account` (`account_id`),
  KEY `idx_team_shift_timing_active` (`is_active`),
  KEY `idx_team_shift_timing_order` (`order_index`),
  CONSTRAINT `team_shift_timing_configs_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `team` (`id`),
  CONSTRAINT `team_shift_timing_configs_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;