"""Add team roster tables

Revision ID: team_roster_v1
Revises: 
Create Date: 2024-12-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'team_roster_v1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create team_shift_configs table
    op.create_table('team_shift_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('shift_name', sa.String(64), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=True, default=0),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create roster_assignments table
    op.create_table('roster_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('shift_config_id', sa.Integer(), nullable=False),
        sa.Column('assignment_date', sa.Date(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['shift_config_id'], ['team_shift_configs.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes
    op.create_index('idx_roster_assignment_date', 'roster_assignments', ['assignment_date'], unique=False)
    op.create_index('idx_roster_assignment_team_date', 'roster_assignments', ['team_id', 'assignment_date'], unique=False)
    
    # Create unique constraint for roster assignments
    op.create_unique_constraint('unique_assignment_per_shift_date', 'roster_assignments', 
                              ['team_id', 'user_id', 'shift_config_id', 'assignment_date'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_assignment_per_shift_date', 'roster_assignments', type_='unique')
    op.drop_index('idx_roster_assignment_team_date', table_name='roster_assignments')
    op.drop_index('idx_roster_assignment_date', table_name='roster_assignments')
    op.drop_table('roster_assignments')
    op.drop_table('team_shift_configs')
    # ### end Alembic commands ###